version: '3.7'

services:
    database:
        image: mcr.microsoft.com/mssql/server
        container_name: mssql
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=*4072300Dev
        networks: 
            - "dockertnet"

    api:
        build: .
        container_name: api
        ports: 
            - "3000:3000"
        volumes: 
            - ".:/usr/src/api"
            - "/usr/src/api/node_modules"
        networks: 
            - "dockertnet"
        depends_on: 
            - database
        environment:
            - DIALECT=mssql
            - DB_HOST=database
            - DB_USER=sa
            - DB_PASSWORD=*4072300Dev
            - DATABASE=TWA_Dev
        
    networks: 
        dockertnet:
            driver: bridge