version: '3.7'

services:

    reverse_proxy:
        image: nginx
        container_name: reverse_proxy
        depends_on: 
            - database
            - api
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
        networks: 
            - "dockertnet"

    database:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=*4072300Dev
        ports: 
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: on-failure
        networks: 
            - "dockertnet"

    api:
        build: .
        container_name: api
        ports: 
            - "3000:3000"
        volumes: 
            - ".:/usr/src/api"
            - "/usr/src/api/node_modules"
        depends_on: 
            - database
        environment:
            - DIALECT=postgres
            - DB_HOST=database
            - DB_USER=stgonzales
            - DB_PASSWORD=*4072300Dev
            - DATABASE=TWA_Dev
            - PORT=3000
        restart: on-failure
        networks: 
            - "dockertnet"
    
networks: 
    dockertnet:
        driver: bridge