version: '3.7'

services:

    nginx:
        container_name: nginx
        image: nginx:latest
        ports: 
            - 80:80
            - 443:443
        depends_on: 
            - database
            - api
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/ssl/dh/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker-volumes/etc/letsencrypt/live/iamgonzales.dev/fullchain.pem
            - /docker-volumes/etc/letsencrypt/live/iamgonzales.dev/privkey.pem
        restart: unless-stopped
        networks: 
            - "dockernet"

    database:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=*4072300Dev
        ports: 
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
        networks: 
            - "dockernet"

    api:
        build: .
        container_name: api
        ports: 
            - "3000:3000"
        volumes: 
            - ".:/usr/src/api"
            - "/usr/src/api/node_modules"
        depends_on: 
            - database
        environment:
            - DIALECT=postgres
            - DB_HOST=database
            - DB_USER=stgonzales
            - DB_PASSWORD=*4072300Dev
            - DATABASE=TWA_Dev
            - PORT=3000
        restart: unless-stopped
        networks: 
            - "dockernet"
    
    networks: 
        dockernet:
            driver: bridge 